<h1>Импорт библиотек

In [2]:
import numpy as np
import matplotlib.pyplot as plt


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Demi\AppData\Roaming\Python\Python312\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "C:\Users\Demi\AppData\Roaming\Python\Python312\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\Demi\AppData\Roaming\Python\Python312\site-packages\ipykernel\kernelapp.py", line 739, in start
    self.io_loop.

ImportError: 
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.



ImportError: initialization failed

<h1>Задача 1. Дан набор из $p$ матриц размерностью $(n, n)$ и $p$ векторов размерностью $(n, 1)$, найти сумму произведений матриц на векторы. Написать тесты для кода

In [6]:
def sum_prod(matrices, vectors):
    if len(matrices) != len(vectors):
        raise ValueError("Количество матриц должно совпадать с количеством векторов")
    
    result = np.zeros(matrices[0].shape[0])
    
    for matrix, vector in zip(matrices, vectors):
        result += np.dot(matrix, vector).flatten()
    
    return result

if __name__ == "__main__":

    matrix3 = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
    vector3 = np.array([[1], [2], [3]])
    
    matrices = [matrix3]
    vectors = [vector3]
    
    result = sum_prod(matrices, vectors)
    print(result)  # Ожидаем [1. 2. 3.], так как это единичная матрица

    matrix4 = np.array([[2, 0], [0, 2]])
    vector4 = np.array([[3], [4]])
    
    matrices = [matrix4]
    vectors = [vector4]
    
    result = sum_prod(matrices, vectors)
    print(result)  # Ожидаем [6. 8.], так как 2*3 = 6 и 2*4 = 8

[1. 2. 3.]
[6. 8.]


<h1>Задача 2. Дана матрица M, напишите функцию, которая бинаризует матрицу по некоторому threshold (то есть, все значения большие threshold становятся равными 1, иначе 0). Напишите тесты для кода

In [9]:
def binarize(M, threshold=0.5):
    return (M > threshold).astype(int)

if __name__ == "__main__":
    M1 = np.array([[0.1, 0.6], [0.4, 0.8]])
    threshold1 = 0.5
    result1 = binarize(M1, threshold1)
    print(result1)  # Ожидаем [[0 1] [0 1]]

    M2 = np.array([[0.5, 0.5], [0.5, 0.5]])
    threshold2 = 0.5
    result2 = binarize(M2, threshold2)
    print(result2)  # Ожидаем [[0 0] [0 0]]

    M3 = np.array([[0.9, 0.1, 0.3], [0.7, 0.2, 0.8]])
    threshold3 = 0.4
    result3 = binarize(M3, threshold3)
    print(result3)  # Ожидаем [[1 0 0] [1 0 1]]

    M4 = np.array([[1.0, 0.0], [0.0, 1.0]])
    threshold4 = 0.5
    result4 = binarize(M4, threshold4)
    print(result4)  # Ожидаем [[1 0] [0 1]]

    M5 = np.array([[0.2, 0.3], [0.1, 0.4]])
    threshold5 = 0.5
    result5 = binarize(M5, threshold5)
    print(result5)  # Ожидаем [[0 0] [0 0]]

[[0 1]
 [0 1]]
[[0 0]
 [0 0]]
[[1 0 0]
 [1 0 1]]
[[1 0]
 [0 1]]
[[0 0]
 [0 0]]


<h1>Задача 3. Напишите функцию, которая возвращает уникальные элементы из каждой строки матрицы. Напишите такую же функцию, но для столбцов. Напишите тесты для кода

In [11]:
def unique_rows(mat):
    return np.array([np.unique(row) for row in mat])

def unique_columns(mat):
    unique_cols = [np.unique(mat[:, col]) for col in range(mat.shape[1])]
    max_length = max(len(col) for col in unique_cols)
    result = np.full((max_length, len(unique_cols)), np.nan)
    for i, col in enumerate(unique_cols):
        result[:len(col), i] = col
    return result

if __name__ == "__main__":
    mat = np.array([[1, 2, 2, 3],
                    [4, 5, 5, 6],
                    [1, 2, 3, 3]])


    unique_rows_result = unique_rows(mat)
    print("Unique rows:")
    print(unique_rows_result)  # Ожидаем [[1 2 3] [4 5 6] [1 2 3]]

    unique_columns_result = unique_columns(mat)
    print("Unique columns:")
    print(unique_columns_result)  # Ожидаем [[1 4] [2 5] [3 6]]

Unique rows:
[[1 2 3]
 [4 5 6]
 [1 2 3]]
Unique columns:
[[ 1.  2.  2.  3.]
 [ 4.  5.  3.  6.]
 [nan nan  5. nan]]


<h1>Задача 4. Напишите функцию, которая заполняет матрицу с размерами $(m, n)$ случайными числами, распределенными по нормальному закону. Затем считает мат. ожидание и дисперсию для каждого из столбцов и строк, а также строит для каждой строки и столбца гистограмму значений (использовать функцию hist из модуля matplotlib.plot)

In [ ]:
# Your code goes here

<h1>Задача 5. Напишите функцию, которая заполняет матрицу $(m, n)$ в шахматном порядке заданными числами $a$ и $b$. Напишите тесты для кода

In [ ]:
def chess(m, n, a, b):
    # Your code goes here
    pass

<h1>Задача 6. Напишите функцию, которая отрисовывает прямоугольник с заданными размерами (a, b) на изображении размера (m, n), цвет фона задайте в схеме RGB, как и цвет прямоугольника. Цвета также должны быть параметрами функции. Напишите аналогичную функцию но для овала с полуосями a и b. Напишите тесты для кода.
Примечание: уравнение эллипса (границы овала) можно записать как:
<h1>$\frac{(x-x_0)^2}{a^2}+\frac{(y-y_0)^2}{b^2}=1$

In [1]:
def draw_rectangle(a, b, m, n, rectangle_color, background_color):
    # Your code goes here
    pass

def draw_ellipse(a, b, m, n, ellipse_color, background_color):
    # Your code goes here
    pass

<h1>Задача 7. Дан некий временной ряд. Для данного ряда нужно найти его: математическое ожидание, дисперсию, СКО, найти все локальные максимумы и минимумы (локальный максимум - это точка, которая больше своих соседних точек, а локальный минимум - это точка, которая меньше своих соседей), а также вычислить для данного ряда другой ряд, получаемый методом скользящего среднего с размером окна $p$.
<h1>Примечание: метод скользящего среднего подразумевает нахождение среднего из подмножетсва ряда размером $p$

In [ ]:
# Your code goes here

<h1> Задача 8. Дан некоторый вектор с целочисленными метками классов, напишите функцию, которая выполняет one-hot-encoding для данного вектора
<h1> One-hot-encoding - представление, в котором на месте метки некоторого класса стоит 1, в остальных позициях стоит 0. Например для вектора [0, 2, 3, 0] one-hot-encoding выглядит как: [[1, 0, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1], [1, 0, 0, 0]]

In [ ]:
# Your code goes here